
# This file is automatically generated, you probably don't want to edit this

RjOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "RjOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            code = NULL,
            R = NULL,
            vars = NULL, ...) {

            super$initialize(
                package='Rj',
                name='Rj',
                requiresData=TRUE,
                ...)

            private$..code <- jmvcore::OptionString$new(
                "code",
                code,
                hidden=TRUE)
            private$..R <- jmvcore::OptionList$new(
                "R",
                R,
                options=list(
                    "bundled",
                    "external"))
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                hidden=TRUE)

            self$.addOption(private$..code)
            self$.addOption(private$..R)
            self$.addOption(private$..vars)
        }),
    active = list(
        code = function() private$..code$value,
        R = function() private$..R$value,
        vars = function() private$..vars$value),
    private = list(
        ..code = NA,
        ..R = NA,
        ..vars = NA)
)

RjResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="R")}))

RjBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "RjBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'Rj',
                name = 'Rj',
                version = c(1,0,0),
                options = options,
                results = RjResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' R
#'
#' 
#' @param data .
#' @param code .
#' @param R .
#' @param vars .
#' @return A results object containing:
#' \tabular{llllll}{
#' }
#'
#' @export
Rj <- function(
    data,
    code,
    R,
    vars) {

    if ( ! requireNamespace('jmvcore'))
        stop('Rj requires jmvcore to be installed (restart may be required)')

    options <- RjOptions$new(
        code = code,
        R = R,
        vars = vars)

    results <- RjResults$new(
        options = options)

    analysis <- RjClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
